In [64]:
pip install np_utils

Requirement already satisfied: np_utils in c:\users\neeraj\anaconda3\lib\site-packages (0.5.12.1)
Requirement already satisfied: future>=0.16 in c:\users\neeraj\anaconda3\lib\site-packages (from np_utils) (0.18.2)
Requirement already satisfied: numpy>=1.0 in c:\users\neeraj\anaconda3\lib\site-packages (from np_utils) (1.19.5)
Note: you may need to restart the kernel to use updated packages.

In [76]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [77]:
df = pd.read_csv('diabetes.csv') 
print(df.shape)
df.describe()

(768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [83]:
target_column = ['Age'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.226180,0.607510,0.566438,0.207439,0.094326,0.476790,0.194990,0.410381,0.348958
std,0.198210,0.160666,0.158654,0.161134,0.136222,0.117499,0.136913,0.145188,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032231,0.259259,0.000000
25%,0.058824,0.497487,0.508197,0.000000,0.000000,0.406855,0.100723,0.296296,0.000000
50%,0.176471,0.587940,0.590164,0.232323,0.036052,0.476900,0.153926,0.358025,0.000000
75%,0.352941,0.704774,0.655738,0.323232,0.150414,0.545455,0.258781,0.506173,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [84]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)

In [88]:
# one hot encode outputs
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

count_classes = y_test.shape[1]
print(count_classes)

2

In [89]:
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=8))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

In [90]:
# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
# build the model
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
17/17 [==============================] - 10s 4ms/step - loss: 0.4451 - accuracy: 0.9635
Epoch 2/20
17/17 [==============================] - 0s 6ms/step - loss: 0.0101 - accuracy: 1.0000
Epoch 3/20
17/17 [==============================] - 0s 8ms/step - loss: 1.8052e-04 - accuracy: 1.0000
Epoch 4/20
17/17 [==============================] - 0s 6ms/step - loss: 8.6396e-05 - accuracy: 1.0000
Epoch 5/20
17/17 [==============================] - 0s 5ms/step - loss: 5.9899e-05 - accuracy: 1.0000
Epoch 6/20
17/17 [==============================] - 0s 5ms/step - loss: 3.6063e-05 - accuracy: 1.0000
Epoch 7/20
17/17 [==============================] - 0s 6ms/step - loss: 2.3770e-05 - accuracy: 1.0000
Epoch 8/20
17/17 [==============================] - 0s 8ms/step - loss: 2.6154e-05 - accuracy: 1.0000
Epoch 9/20
17/17 [==============================] - 0s 5ms/step - loss: 2.3318e-05 - accuracy: 1.0000
Epoch 10/20
17/17 [==============================] - ETA: 0s - loss: 1.1082e-05 - accuracy: 1.00 - 0s 15ms/step - loss: 1.1366e-05 - accuracy: 1.0000
Epoch 11/20
17/17 [==============================] - 0s 6ms/step - loss: 1.1464e-05 - accuracy: 1.0000
Epoch 12/20
17/17 [==============================] - 0s 9ms/step - loss: 9.8123e-06 - accuracy: 1.0000
Epoch 13/20
17/17 [==============================] - 0s 10ms/step - loss: 5.8418e-06 - accuracy: 1.0000
Epoch 14/20
17/17 [==============================] - 0s 6ms/step - loss: 6.3888e-06 - accuracy: 1.0000
Epoch 15/20
17/17 [==============================] - 0s 6ms/step - loss: 4.2018e-06 - accuracy: 1.0000
Epoch 16/20
17/17 [==============================] - 0s 5ms/step - loss: 3.7410e-06 - accuracy: 1.0000
Epoch 17/20
17/17 [==============================] - 0s 6ms/step - loss: 3.5079e-06 - accuracy: 1.0000
Epoch 18/20
17/17 [==============================] - 0s 5ms/step - loss: 2.8888e-06 - accuracy: 1.0000
Epoch 19/20
17/17 [==============================] - 0s 6ms/step - loss: 3.6142e-06 - accuracy: 1.0000
Epoch 20/20
17/17 [==============================] - 0s 5ms/step - loss: 1.6166e-06 - accuracy: 1.0000

In [ ]:
pred_train= model.predict(X_train)
scores = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_test= model.predict(X_test)
scores2 = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))