In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("agra_potato.csv")
df.head()

,"Min,Max,Modal Price from Uttar Pradesh,Agra[Potato],Agra from 01-Jan-2020To31-Dec-2020 (Total-285) (Total-285)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date
1,1,Agra,Agra,Potato,Desi,FAQ,800,1100,960,31-Dec-20
2,2,Agra,Agra,Potato,Desi,FAQ,800,1050,940,30-Dec-20
3,3,Agra,Agra,Potato,Desi,FAQ,800,1080,950,29-Dec-20
4,4,Agra,Agra,Potato,Desi,FAQ,800,1100,950,28-Dec-20